apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: go-web-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: go-web
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sample-web-application

spec:
  selector:
    matchLabels:
      app: go-web
  replicas: 2
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
      - name: sample-web-application
        image: runq/go-web:latest
        imagePullPolicy: Always