apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: go-web-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: sample-web
    app.kubernetes.io/version: 1.0.1
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sample-application

spec:
  selector:
    matchLabels:
      app: sample-web
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-web
    spec:
      containers:
      - name: sample-web-go
        image: docker.pkg.github.com/aka-achu/go-web/sample:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: registry-secret