name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
          name: Login to Dockerhub
          uses: docker/login-action@v1
          with: 
            username: akaachu
            password: ${{ secrets.HUB_ACCESS_TOKEN }}
      -
         name: Build and Push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           context: .
           file: ./build/Dockerfile
           push: true
           tags: runq/go-web:latest
      -
         name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
